import type { Evidence, Opportunity } from "./types";

export const evidence: Evidence[] = [
  {
    id: "nonprofit",
    capability: "Business model",
    level: "public",
    signal: "AP describes itself as an independent global news organization founded in 1846 as a news cooperative whose members are U.S. newspapers and broadcasters.",
    conclusion: "Reader support is a mission relationship, not a paywall. The ask has to be earned and explained.",
    implication: "Treat every donation ask as a trust event with a reason, a cap, and a quiet fallback.",
    source: "ap.org / About",
    url: "https://www.ap.org/about/",
  },
  {
    id: "reach",
    capability: "Audience reach",
    level: "public",
    signal: "AP states that four billion people see AP journalism every day and that it has journalists in nearly 100 countries.",
    conclusion: "Most encounters with AP journalism happen off apnews.com, on member and customer surfaces.",
    implication: "Model the member-site and aggregator handoff as a first-class origin, not as untracked referral noise.",
    source: "ap.org / Our reach",
    url: "https://www.ap.org/about/",
  },
  {
    id: "donate",
    capability: "Donation surface",
    level: "observed",
    signal: "apnews.com/donate is a live page titled “Donate to The AP”, linked from the site footer.",
    conclusion: "A donation path already exists. The open question is when and to whom it is presented.",
    implication: "Route the ask by context and relationship state rather than by placement alone.",
    source: "apnews.com/donate",
    url: "https://apnews.com/donate",
  },
  {
    id: "newsletters",
    capability: "First-party sign-up",
    level: "observed",
    signal: "apnews.com/newsletters offers The Morning Wire and The Afternoon Wire, the latter described as sent by a personalization engine.",
    conclusion: "Email is the primary first-party relationship, and personalization already depends on it.",
    implication: "Make section-relevant newsletter sign-up the default first ask for engaged anonymous readers.",
    source: "apnews.com/newsletters",
    url: "https://apnews.com/newsletters",
  },
  {
    id: "account",
    capability: "Registered identity",
    level: "observed",
    signal: "The site header exposes “Sign in” and “My Account”, and the footer links to the AP News mobile apps.",
    conclusion: "A registered layer exists above email, and the app is a separate habit surface.",
    implication: "Ladder the relationship: email, then account with saves and alerts, then app, then support.",
    source: "apnews.com header and footer",
    url: "https://apnews.com/",
  },
  {
    id: "sections",
    capability: "Editorial context",
    level: "observed",
    signal: "Navigation spans World, U.S., Politics, Sports, Business, Science, Fact Check, Climate, Health, Lifestyle, Religion and Español.",
    conclusion: "Reader intent differs sharply by section; a Fact Check reader and a Sports reader arrive for different reasons.",
    implication: "Give each section its own thresholds, utility and donation framing inside one policy contract.",
    source: "apnews.com navigation",
    url: "https://apnews.com/",
  },
  {
    id: "dnr-2026",
    capability: "Market reality",
    level: "public",
    signal: "The Reuters Institute reports social and video reaching more news audiences than owned sites and apps, with paid online news flat at 17% and lower in the U.S.",
    conclusion: "Distribution is fragmenting and willingness to pay is not growing on its own.",
    implication: "Prioritize the attributable path from borrowed attention to owned habit, then to support.",
    source: "Reuters Institute Digital News Report 2026",
    url: "https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2026/dnr-executive-summary",
  },
  {
    id: "ai-referral",
    capability: "AI discovery",
    level: "public",
    signal: "AI assistants increasingly answer news questions directly and cite sources, sending fewer but higher-intent visits back to publishers.",
    conclusion: "An assistant referral is a rare, high-intent moment that should not be spent on a generic prompt.",
    implication: "Carry origin into the decision so the first owned action is continuity, not a payment ask.",
    source: "Reuters Institute Digital News Report 2026",
    url: "https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2026/dnr-executive-summary",
  },
  {
    id: "breaking",
    capability: "Editorial guardrail",
    level: "proposed",
    signal: "Breaking and safety-relevant coverage draws the largest anonymous spikes and the lowest tolerance for interruption.",
    conclusion: "The moment with the most traffic is the worst moment to fundraise.",
    implication: "Suppress payment asks in breaking mode; offer alerts only when consent allows.",
    source: "Next Best Ask policy",
    url: "#lab",
  },
  {
    id: "fatigue",
    capability: "Ask frequency",
    level: "proposed",
    signal: "The same reader can be eligible for a newsletter prompt, an account prompt, an app banner and a donation ask on one visit.",
    conclusion: "Locally optimized asks produce a globally incoherent experience and erode trust.",
    implication: "Enforce one weekly ask budget per reader and log every exposure against it.",
    source: "Next Best Ask policy",
    url: "#lab",
  },
  {
    id: "donor-truth",
    capability: "Donor recognition",
    level: "proposed",
    signal: "A donor who is shown an acquisition ask learns that the relationship was not recorded.",
    conclusion: "Donor state is an entitlement, and false negatives are a trust failure, not a missed conversion.",
    implication: "Hold donors in a permanent holdout for acquisition asks and measure recognition accuracy.",
    source: "Next Best Ask policy",
    url: "#lab",
  },
  {
    id: "decision-layer",
    capability: "Orchestration layer",
    level: "proposed",
    signal: "Donation, newsletter, account, app and advertising decisions are typically owned by different teams and tools.",
    conclusion: "Without a shared contract, each team optimizes its own ask against the same reader.",
    implication: "Add a thin, explainable policy service with a canonical exposure event.",
    source: "Next Best Ask proposal",
    url: "#lab",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "ask-budget",
    horizon: "90 days",
    domain: "Trust",
    title: "One ask budget per reader",
    thesis: "Put newsletter, account, app and donation prompts on a shared weekly budget with a canonical exposure event, so no reader sees four asks in one visit.",
    metric: "Asks per reader-week · prompt dismiss rate · return rate",
    impact: 5,
    confidence: 5,
    effort: 2,
  },
  {
    id: "signup-ladder",
    horizon: "90 days",
    domain: "First-party data",
    title: "Section-relevant sign-up ladder",
    thesis: "Replace the generic newsletter prompt with the section's most useful continuity: Morning Wire for Politics, alerts for Fact Check, scores for Sports.",
    metric: "Sign-ups per 1k engaged sessions · 30-day open rate",
    impact: 5,
    confidence: 4,
    effort: 2,
  },
  {
    id: "origin-contract",
    horizon: "90 days",
    domain: "Distribution",
    title: "Origin-aware first action",
    thesis: "Normalize search, social, aggregator, AI assistant and member-site arrivals into the same context envelope and pick continuity before payment.",
    metric: "Attributed handoffs · unknown-origin rate · sign-up by origin",
    impact: 4,
    confidence: 4,
    effort: 2,
  },
  {
    id: "donor-recognition",
    horizon: "90 days",
    domain: "Reliability",
    title: "Donor recognition scorecard",
    thesis: "Measure how often a current donor is shown an acquisition ask, and treat that number like an entitlement outage.",
    metric: "Donor false-ask rate · recognition latency",
    impact: 5,
    confidence: 5,
    effort: 2,
  },
  {
    id: "known-reader-ask",
    horizon: "90 days",
    domain: "Donations",
    title: "Known-reader donation pilot",
    thesis: "On one section, make the donation ask only to readers with an email relationship and a mission-affinity signal, with a clean holdout.",
    metric: "Gifts per 1k known sessions · gift size · unsubscribe rate",
    impact: 5,
    confidence: 4,
    effort: 3,
  },
  {
    id: "breaking-mode",
    horizon: "90 days",
    domain: "Trust",
    title: "Breaking-news ask suppression",
    thesis: "Flag breaking and safety coverage in the context contract and suppress payment asks automatically, offering alerts instead.",
    metric: "Asks during breaking · alert opt-ins · complaint volume",
    impact: 4,
    confidence: 5,
    effort: 1,
  },
  {
    id: "stewardship",
    horizon: "2–4 quarters",
    domain: "Donations",
    title: "Stewardship and monthly upgrade loop",
    thesis: "Pair one-time gifts with an impact report, a thank-you state on site, and a single well-timed invitation to monthly support.",
    metric: "Monthly conversion · 12-month donor retention",
    impact: 5,
    confidence: 4,
    effort: 3,
  },
  {
    id: "policy-service",
    horizon: "2–4 quarters",
    domain: "First-party data",
    title: "Reader relationship policy service",
    thesis: "Separate global guardrails (consent, breaking, fatigue, donor protection) from section-owned thresholds and treatments.",
    metric: "Decision coverage · policy change cycle time",
    impact: 5,
    confidence: 4,
    effort: 4,
  },
  {
    id: "member-handoff",
    horizon: "2–4 quarters",
    domain: "Distribution",
    title: "Member-site relationship handoff",
    thesis: "Give readers who meet AP journalism on member and customer sites a privacy-safe path to an AP relationship without competing with the member.",
    metric: "Handoffs per 1k member exposures · member-safe attribution",
    impact: 4,
    confidence: 3,
    effort: 4,
  },
  {
    id: "direct-index",
    horizon: "2–4 quarters",
    domain: "First-party data",
    title: "Durable relationship index",
    thesis: "Unify newsletter, account, app, alert and donor activity into one audience measure that can outlive search and social traffic.",
    metric: "Durable relationships / 1k content encounters",
    impact: 5,
    confidence: 4,
    effort: 4,
  },
];

export const architecture = [
  { id: "distribution", label: "Distribution edge", note: "Search · social · aggregators · AI · member sites", level: "public" },
  { id: "experience", label: "Story experience", note: "Section · story mode · surfaces", level: "observed" },
  { id: "signals", label: "Signal plane", note: "Visits · minutes · mission affinity · consent", level: "proposed" },
  { id: "identity", label: "Reader relationship", note: "Email · account · donor state", level: "observed" },
  { id: "decision", label: "Ask policy", note: "Guardrails · score · arbitration · fallback", level: "proposed" },
  { id: "systems", label: "Execution systems", note: "Newsletter · account · app · donation · ads", level: "public" },
  { id: "truth", label: "Outcome truth", note: "Exposure · sign-up · gift · retention", level: "proposed" },
] as const;

export const sectionOptions = [
  { id: "politics", label: "Politics", note: "Habit + accountability" },
  { id: "world", label: "World", note: "On-the-ground reporting" },
  { id: "fact-check", label: "Fact Check", note: "Trust + verification" },
  { id: "sports", label: "Sports", note: "Habit + alerts" },
] as const;

export const originOptions = [
  { id: "direct", label: "Direct / owned", note: "Typed, app, newsletter or bookmark" },
  { id: "search", label: "Search", note: "Traditional search referral" },
  { id: "social-video", label: "Social video", note: "Creator or social discovery" },
  { id: "aggregator", label: "News aggregator", note: "Google News, Apple News, MSN" },
  { id: "ai-assistant", label: "AI assistant", note: "Cited answer with a link back" },
  { id: "member-site", label: "Member / customer site", note: "AP story on a member outlet" },
] as const;

export const storyModeOptions = [
  { id: "standard", label: "Standard story" },
  { id: "breaking", label: "Breaking news" },
  { id: "evergreen", label: "Evergreen / explainer" },
] as const;
